### PR TITLE
was not able to identify one consumer from another, working on #43

### LINKED ISSUE #43: Auth tokens need to be specific to consumer
Each consumer needs a unique token.

### PR DESCRIPTION
**Pull request by wcjr**
resolves #43

### CODE REVIEW

**Comment by forevermatt** [comment]
It's kind of funny, this is almost exactly what I ended up doing in ID Sync:
https://github.com/silinternational/idp-id-sync/blob/develop/application/common/components/ApiConsumer.php

**Comment by wcjr** [comment]
funny :-)  

I suppose I need to understand the significance of forcing `true` in the array check?  What use case are you protecting against there?

Additionally, should I be using `params` too?

**Comment by forevermatt** [comment]
True is to force a strict comparison (checking type specifically, rather than allowing type-casting) so that something like `false` isn't considered to match an empty string (`''`), which otherwise could happen:
```
> php -r "var_dump(in_array(false, ['']), in_array(false, [''], true));"
bool(true)
bool(false)
```
I don't know whether there's actually a chance of hitting that here, but using `true` for the strict comparison removes the risk.

**Comment by forevermatt** [comment]
As far as using `params`, it just felt like it was more in line with the way Yii expects you to provide it configuration details (rather than grabbing them from the environment variables directly within your normal code, almost like some global variable). Not mandatory, but it seems like a better practice.

**Comment by wcjr** [comment]
gotcha, I'll go back and refactor those then...I also noticed now that I didn't use the Sil version of the env getter.

**Comment by wcjr** [comment]
Thanks again @forevermatt , took care of these in #53

**Pull request merged**
