### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by forevermatt**

### CODE REVIEW

**Review by Schparky — APPROVED** [review]
Does this address a vulnerability or a specific deficiency?

Also, would you like to revise the `depsupdate` script to do this?
```
depsupdate:
	docker-compose run --rm cli bash -c "composer update --no-scripts && composer show -Df json > versions.json"
```

**Comment by forevermatt** [comment]
> Does this address a vulnerability or a specific deficiency?

It addresses a vulnerability.

> Also, would you like to revise the `depsupdate` script to do this?
> 
> ```
> depsupdate:
> 	docker-compose run --rm cli bash -c "composer update --no-scripts && composer show -Df json > versions.json"
> ```

Sure thing. Thanks.

**Comment by forevermatt** [comment]
@Schparky - Actually, I'll update the code to show the direct dependencies (as JSON) in a separate PR, so that we can merge that first and update this PR to show what it changes.

**Comment by Schparky** [comment]
> @Schparky - Actually, I'll update the code to show the direct dependencies (as JSON) in a separate PR, so that we can merge that first and update this PR to show what it changes.

Even better! :100:

**Comment by forevermatt** [comment]
> Even better! 💯

Here you go: #247

**Review by jason-jackson — APPROVED** [review]

**Review by Schparky — APPROVED** [review]

**Pull request merged**
