### PR TITLE
Release 6.10.4 - Update dependencies

### PR DESCRIPTION
**Pull request by forevermatt**
### Fixed
- Update dependencies

---

### PR Checklist
- [x] Put version number in PR title (e.g. `Release x.y.z - Summary of changes`)
- [x] Run `make composershow`
- [x] Run `make psr2`

### CODE REVIEW

**Review by briskt — APPROVED** [review]
Looks like we need to fix the workflow to not push to GHCR on feature branches, or we need to not use slashes in branch names.

**Comment by forevermatt** [comment]
> Looks like we need to fix the workflow to not push to GHCR on feature branches, or we need to not use slashes in branch names.

Yeah, I noticed that and was wondering what to do about it. Apparently there's an output you can use for getting those tags (hopefully in a format that works for tags, i.e. replacing slashes with hyphens). I'm also fine with only pushing docker images for the `main` branch, if you prefer that approach.

**Comment by forevermatt** [comment]
> > Looks like we need to fix the workflow to not push to GHCR on feature branches, or we need to not use slashes in branch names.
> 
> Yeah, I noticed that and was wondering what to do about it. Apparently there's an output you can use for getting those tags (hopefully in a format that works for tags, i.e. replacing slashes with hyphens). I'm also fine with only pushing docker images for the `main` branch, if you prefer that approach.

Here's the approach using and output to get the tags, but I don't know if we need to upgrade to version 6 of that GitHub Action to be able to use it (I would _guess_ not...):
https://docs.docker.com/build/ci/github-actions/manage-tags-labels/#:~:text=steps.meta.outputs.tags

**Comment by briskt** [comment]
> I'm also fine with only pushing docker images for the `main` branch, if you prefer that approach.

That's the direction I've been going lately.

**Pull request merged**
